name: Docs Actions Build

env:
  deployToRepo: gh-pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches history for real dates

      - name: Fix Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Speed up future builds

      - name: Install dependencies
        run: pnpm install

      - name: Index pages
        run: pnpm run gensearch

      - name: Build
        run: |
          pnpm run build
          touch ./dist/.nojekyll

      - name: Push to pages repo
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: 'dist'
          branch: gh-pages
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          commit-message: Deploy Site
