name: Docs Actions Build

env:
  deployToRepo: gh-pages

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        
      # Setup pnpm
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.4.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies with pnpm
      - name: Install dependencies
        run: pnpm i

      # Generate the search index tree
      - name: Index pages
        run: |
          pnpm run gensearch

      # Regenerate the search index tree, build the project, and add .nojekyll file to supress default behaviour
      - name: Build
        run: |
          pnpm run build
          touch ./dist/.nojekyll

      # Push to your pages repo
      - name: Push to pages repo
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: 'dist'
          branch: gh-pages
          git-config-name: GitHub Actions
          git-config-email: actions@github.com"
          commit-message: Deploy Site